markdown: rdiscount
pygments: true
#permalink: :categories/:year/:month/:day/:title 
permalink: :categories/:title 
title : 会飞de树's GAE
author :
  name : 会飞de树
  email : wellwy@gmail.com
  github : wellwy
  twitter : 
  feedburner : 

baseurl : /gae
homepage : /index.html
graphs : /gae/include/graphs
static_metro : http://wellwy.github.io/static/include/metro

comments: true
googleAnalytics : true
